// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System.Collections.Generic;
using UnityEngine;

namespace JumpyWorld
{
	public class MixpanelInit : MonoBehaviour
	{
		public string token = "87257aeb7ebfa610ed50736aa131a3b2";

		void Start() {
			Mixpanel.Token = token;
			Mixpanel.DistinctID = SystemInfo.deviceUniqueIdentifier;
			Mixpanel.SendEvent ("Start");
		}

		void OnApplicationQuit() {
			Mixpanel.SendEvent ("End", new Dictionary<string,object> {
				{"Duration" , Time.time}
			});
		}
	}
}

